### ISSUE TITLE
not sure if this is still maintained but know that you can now remove the `backtrace` feature

### ISSUE THREAD

**Issue by jondot** [yaahc/btparse#4]
so that this can be compatible with today's stable.

IMHO, even though it parses a debug representation, this crate is still very useful especially since error API surface requires unstable for using provide and request. So it's possibly the only option for stable if someone wants to use std::backtrace

**Comment by jondot** [comment]
I did it here:
https://github.com/jondot/btparse

which is being used here: https://github.com/jondot/backtrace_printer (based on YOUR idea actually in some of the `thiserror` threads 😄 )

which eventually, is being used in Loco: https://loco.rs/ , which yields this nice experience:
<img width="1328" alt="image" src="https://github.com/yaahc/btparse/assets/83390/94a01204-d0e5-40df-a56b-55135f758ad1">

**Comment by yaahc** [comment]
it's still lowkey maintained, tho I probably won't fix this myself, but if you wanna open a PR with your fix I'll happily review and merge it and push a new release for it
